In [1]:
import pandas as pd

In [2]:
solar_weather=pd.read_csv("solar_weather.csv")

In [3]:
solar_weather.head()

,Time,Energy delta[Wh],GHI,temp,pressure,humidity,wind_speed,rain_1h,snow_1h,clouds_all,isSun,sunlightTime,dayLength,SunlightTime/daylength,weather_type,hour,month
0,2017-01-01 00:00:00,0,0.0,1.6,1021,100,4.9,0.0,0.0,100,0,0,450,0.0,4,0,1
1,2017-01-01 00:15:00,0,0.0,1.6,1021,100,4.9,0.0,0.0,100,0,0,450,0.0,4,0,1
2,2017-01-01 00:30:00,0,0.0,1.6,1021,100,4.9,0.0,0.0,100,0,0,450,0.0,4,0,1
3,2017-01-01 00:45:00,0,0.0,1.6,1021,100,4.9,0.0,0.0,100,0,0,450,0.0,4,0,1
4,2017-01-01 01:00:00,0,0.0,1.7,1020,100,5.2,0.0,0.0,100,0,0,450,0.0,4,1,1

In [4]:
solar_weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 196776 entries, 0 to 196775
Data columns (total 17 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Time                    196776 non-null  object
 1   Energy delta[Wh]        196776 non-null  int64
 2   GHI                     196776 non-null  float64
 3   temp                    196776 non-null  float64
 4   pressure                196776 non-null  int64
 5   humidity                196776 non-null  int64
 6   wind_speed              196776 non-null  float64
 7   rain_1h                 196776 non-null  float64
 8   snow_1h                 196776 non-null  float64
 9   clouds_all              196776 non-null  int64
 10  isSun                   196776 non-null  int64
 11  sunlightTime            196776 non-null  int64
 12  dayLength               196776 non-null  int64
 13  SunlightTime/daylength  196776 non-null  float64
 14  weather_type            196776 non-null  int64
 15  hour                    196776 non-null  int64
 16  month                   196776 non-null  int64
dtypes: float64(6), int64(10), object(1)
memory usage: 25.5+ MB

In [5]:
solar_weather.shape

(196776, 17)

In [6]:
solar_weather['Time']=pd.to_datetime(solar_weather['Time'])

In [7]:
solar_weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 196776 entries, 0 to 196775
Data columns (total 17 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Time                    196776 non-null  datetime64[ns]
 1   Energy delta[Wh]        196776 non-null  int64
 2   GHI                     196776 non-null  float64
 3   temp                    196776 non-null  float64
 4   pressure                196776 non-null  int64
 5   humidity                196776 non-null  int64
 6   wind_speed              196776 non-null  float64
 7   rain_1h                 196776 non-null  float64
 8   snow_1h                 196776 non-null  float64
 9   clouds_all              196776 non-null  int64
 10  isSun                   196776 non-null  int64
 11  sunlightTime            196776 non-null  int64
 12  dayLength               196776 non-null  int64
 13  SunlightTime/daylength  196776 non-null  float64
 14  weather_type            196776 non-null  int64
 15  hour                    196776 non-null  int64
 16  month                   196776 non-null  int64
dtypes: datetime64[ns](1), float64(6), int64(10)
memory usage: 25.5 MB

In [8]:
solar_weather.isnull().sum().sort_values()

Time                      0
weather_type              0
SunlightTime/daylength    0
dayLength                 0
sunlightTime              0
isSun                     0
clouds_all                0
hour                      0
snow_1h                   0
wind_speed                0
humidity                  0
pressure                  0
temp                      0
GHI                       0
Energy delta[Wh]          0
rain_1h                   0
month                     0
dtype: int64

In [9]:
null_percentage = (solar_weather.isnull().sum() / len(solar_weather)) * 100
nulls_only = null_percentage[null_percentage > 0].sort_values(ascending=False)

print("Columns with null values:")
print(nulls_only)

Columns with null values:
Series([], dtype: float64)

In [10]:
solar_weather.isnull().sum(axis=1).sort_values()

0         0
131177    0
131178    0
131179    0
131180    0
         ..
65596     0
65597     0
65598     0
65336     0
196775    0
Length: 196776, dtype: int64

In [11]:
solar_weather.describe()

,Time,Energy delta[Wh],GHI,temp,pressure,humidity,wind_speed,rain_1h,snow_1h,clouds_all,isSun,sunlightTime,dayLength,SunlightTime/daylength,weather_type,hour,month
count,196776,196776.000000,196776.000000,196776.000000,196776.000000,196776.000000,196776.000000,196776.000000,196776.000000,196776.000000,196776.000000,196776.000000,196776.000000,196776.000000,196776.000000,196776.000000,196776.000000
mean,2019-10-29 22:44:12.085620992,573.008228,32.596538,9.790521,1015.292780,79.810566,3.937746,0.066035,0.007148,65.974387,0.519962,211.721094,748.644347,0.265187,3.198398,11.498902,6.298329
min,2017-01-01 00:00:00,0.000000,0.000000,-16.600000,977.000000,22.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,450.000000,0.000000,1.000000,0.000000,1.000000
25%,2018-06-02 10:26:15,0.000000,0.000000,3.600000,1010.000000,70.000000,2.600000,0.000000,0.000000,34.000000,0.000000,0.000000,570.000000,0.000000,2.000000,5.000000,3.000000
50%,2019-10-28 20:52:30,0.000000,1.600000,9.300000,1016.000000,84.000000,3.700000,0.000000,0.000000,82.000000,1.000000,30.000000,765.000000,0.050000,4.000000,11.000000,6.000000
75%,2021-03-24 07:18:45,577.000000,46.800000,15.700000,1021.000000,92.000000,5.000000,0.000000,0.000000,100.000000,1.000000,390.000000,930.000000,0.530000,4.000000,17.000000,9.000000
max,2022-08-31 17:45:00,5020.000000,229.200000,35.800000,1047.000000,100.000000,14.300000,8.090000,2.820000,100.000000,1.000000,1020.000000,1020.000000,1.000000,5.000000,23.000000,12.000000
std,NaN,1044.824047,52.172018,7.995428,9.585773,15.604459,1.821694,0.278913,0.069710,36.628593,0.499603,273.902186,194.870208,0.329023,1.289939,6.921887,3.376066

In [12]:
ghi_zero_count = (solar_weather['GHI'] == 0).sum()
total_rows = len(solar_weather)
ghi_zero_percentage = (ghi_zero_count / total_rows) * 100
print(ghi_zero_count)
print(ghi_zero_percentage)

95044
48.30060576493068

In [13]:
energyDelta_zero_count = (solar_weather['Energy delta[Wh]'] == 0).sum()
total_rows = len(solar_weather)
energyDelta_percentage = (energyDelta_zero_count / total_rows) * 100
print(energyDelta_zero_count)
print(energyDelta_percentage)

100850
51.25116884172867

In [14]:
rain1h_zero_count = (solar_weather['rain_1h'] == 0).sum()
total_rows = len(solar_weather)
rain1h_percentage = (rain1h_zero_count / total_rows) * 100
print(rain1h_zero_count)
print(rain1h_percentage)

171808
87.31146074724559

In [15]:
snow1h_zero_count = (solar_weather['snow_1h'] == 0).sum()
total_rows = len(solar_weather)
snow1h_percentage = (snow1h_zero_count / total_rows) * 100
print(snow1h_zero_count)
print(snow1h_percentage)

193036
98.09936171077773

In [16]:
cloudsAll_zero_count = (solar_weather['clouds_all'] == 0).sum()
total_rows = len(solar_weather)
cloudsAll_percentage = (cloudsAll_zero_count / total_rows) * 100
print(cloudsAll_zero_count)
print(cloudsAll_percentage)

13104
6.659348701061105

In [17]:
isSun_zero_count = (solar_weather['isSun'] == 0).sum()
total_rows = len(solar_weather)
isSun_percentage = (isSun_zero_count / total_rows) * 100
print(isSun_zero_count)
print(isSun_percentage)

94460
48.00382160426068

In [18]:
sunlightTime_zero_count = (solar_weather['sunlightTime'] == 0).sum()
total_rows = len(solar_weather)
sunlightTime_percentage = (sunlightTime_zero_count / total_rows) * 100
print(sunlightTime_zero_count)
print(sunlightTime_percentage)

94460
48.00382160426068

In [19]:
dayLength_zero_count = (solar_weather['dayLength'] == 0).sum()
total_rows = len(solar_weather)
dayLength_percentage = (dayLength_zero_count / total_rows) * 100
print(dayLength_zero_count)
print(dayLength_percentage)

0
0.0

In [20]:
SunlightTime_dayLength_zero_count = (solar_weather['SunlightTime/daylength'] == 0).sum()
total_rows = len(solar_weather)
SunlightTime_dayLength_percentage = (SunlightTime_dayLength_zero_count / total_rows) * 100
print(SunlightTime_dayLength_zero_count)
print(SunlightTime_dayLength_percentage)

94460
48.00382160426068

In [21]:
weather_type_zero_count = (solar_weather['weather_type'] == 0).sum()
total_rows = len(solar_weather)
weather_type_percentage = (weather_type_zero_count / total_rows) * 100
print(weather_type_zero_count)
print(weather_type_percentage)

0
0.0

In [22]:
hour_zero_count = (solar_weather['hour'] == 0).sum()
total_rows = len(solar_weather)
hour_percentage = (hour_zero_count / total_rows) * 100
print(hour_zero_count)
print(hour_percentage)

8200
4.167174858722608

In [23]:
month_zero_count = (solar_weather['month'] == 0).sum()
total_rows = len(solar_weather)
month_percentage = (month_zero_count / total_rows) * 100
print(month_zero_count)
print(month_percentage)

0
0.0

In [24]:
solar_weather['Time'] = solar_weather['Time'].apply(lambda x: x.date())
solar_weather.head()

,Time,Energy delta[Wh],GHI,temp,pressure,humidity,wind_speed,rain_1h,snow_1h,clouds_all,isSun,sunlightTime,dayLength,SunlightTime/daylength,weather_type,hour,month
0,2017-01-01,0,0.0,1.6,1021,100,4.9,0.0,0.0,100,0,0,450,0.0,4,0,1
1,2017-01-01,0,0.0,1.6,1021,100,4.9,0.0,0.0,100,0,0,450,0.0,4,0,1
2,2017-01-01,0,0.0,1.6,1021,100,4.9,0.0,0.0,100,0,0,450,0.0,4,0,1
3,2017-01-01,0,0.0,1.6,1021,100,4.9,0.0,0.0,100,0,0,450,0.0,4,0,1
4,2017-01-01,0,0.0,1.7,1020,100,5.2,0.0,0.0,100,0,0,450,0.0,4,1,1

In [25]:
solar_weather['month'] = solar_weather['month'].replace({1:'January', 2:'February', 3:'March', 4:'April', 5:'May', 6:'June', 7:'July', 8:'August', 9:'September', 10:'October', 11:'November', 12:'December'})
solar_weather.head()

,Time,Energy delta[Wh],GHI,temp,pressure,humidity,wind_speed,rain_1h,snow_1h,clouds_all,isSun,sunlightTime,dayLength,SunlightTime/daylength,weather_type,hour,month
0,2017-01-01,0,0.0,1.6,1021,100,4.9,0.0,0.0,100,0,0,450,0.0,4,0,January
1,2017-01-01,0,0.0,1.6,1021,100,4.9,0.0,0.0,100,0,0,450,0.0,4,0,January
2,2017-01-01,0,0.0,1.6,1021,100,4.9,0.0,0.0,100,0,0,450,0.0,4,0,January
3,2017-01-01,0,0.0,1.6,1021,100,4.9,0.0,0.0,100,0,0,450,0.0,4,0,January
4,2017-01-01,0,0.0,1.7,1020,100,5.2,0.0,0.0,100,0,0,450,0.0,4,1,January

Data Interpretation

In [26]:
import matplotlib.pyplot as plt
import seaborn as sns

In [27]:
plt.figure(figsize=(8,6))
sns.barplot(x=solar_weather['month'], y=solar_weather['Energy delta[Wh]'])
plt.title('Chart 01 - Energy based on Month')
plt.xlabel('Month')
plt.xticks(rotation=90)
plt.ylabel('Energy')

The lowest energy producing months are January, November and December.

The Highest energy producing month is June and besides that April, May, July and August are nicely energy producing months.

SyntaxError: invalid syntax (4293003586.py, line 8)

In [ ]:
plt.figure(figsize=(8,6))
sns.lineplot(x=solar_weather['month'], y=solar_weather['GHI'],linewidth=5,errorbar=None)
sns.barplot(x=solar_weather['month'], y=solar_weather['GHI'], errwidth=0)
plt.title('Chart 02 - Solar Radiation based on Month')
plt.xlabel('Month')
plt.xticks(rotation=90)
plt.ylabel('Solar Radiation')

In [ ]:
plt.figure(figsize=(8,6))
sns.histplot(x=solar_weather['month'], hue=solar_weather['weather_type'], palette='coolwarm')
plt.title('Chart 03 - Weather Type vs Month')
plt.xlabel('Month')
plt.xticks(rotation=90)
plt.ylabel('Count')

In [28]:
solar_weather.to_csv("solar_weather_analyzed.csv",index=False)