In [2]:
import pandas as pd

In [3]:
import glob

# Method 1: Direct approach for your specific files
# Read Plant 1 and Plant 2 Generation Data
plant1_gen = pd.read_csv('Plant_1_Generation_Data.csv')
plant2_gen = pd.read_csv('Plant_2_Generation_Data.csv')

# Union ALL (stack vertically) the generation data
generation_data = pd.concat([plant1_gen, plant2_gen], ignore_index=True)

# Read Plant 1 and Plant 2 Weather Sensor Data
plant1_weather = pd.read_csv('Plant_1_Weather_Sensor_Data.csv')
plant2_weather = pd.read_csv('Plant_2_Weather_Sensor_Data.csv')

# Union ALL (stack vertically) the weather sensor data
weather_sensor_data = pd.concat([plant1_weather, plant2_weather], ignore_index=True)

# Optional: Save to new CSV files if needed
generation_data.to_csv('Combined_Generation_Data.csv', index=False)
weather_sensor_data.to_csv('Combined_Weather_Sensor_Data.csv', index=False)

# Display first few rows to verify
print("Generation Data Combined Shape:", generation_data.shape)
print(generation_data.head())
print("\nWeather Sensor Data Combined Shape:", weather_sensor_data.shape)
print(weather_sensor_data.head())

Generation Data Combined Shape: (136476, 7)
          DATE_TIME  PLANT_ID       SOURCE_KEY  DC_POWER  AC_POWER  \
0  15-05-2020 00:00   4135001  1BY6WEcLGh8j5v7       0.0       0.0
1  15-05-2020 00:00   4135001  1IF53ai7Xc0U56Y       0.0       0.0
2  15-05-2020 00:00   4135001  3PZuoBAID5Wc2HD       0.0       0.0
3  15-05-2020 00:00   4135001  7JYdWkrLSPkdwr4       0.0       0.0
4  15-05-2020 00:00   4135001  McdE0feGgRqW7Ca       0.0       0.0

   DAILY_YIELD  TOTAL_YIELD
0          0.0    6259559.0
1          0.0    6183645.0
2          0.0    6987759.0
3          0.0    7602960.0
4          0.0    7158964.0

Weather Sensor Data Combined Shape: (6441, 6)
             DATE_TIME  PLANT_ID       SOURCE_KEY  AMBIENT_TEMPERATURE  \
0  2020-05-15 00:00:00   4135001  HmiyD2TTLFNqkNe            25.184316
1  2020-05-15 00:15:00   4135001  HmiyD2TTLFNqkNe            25.084589
2  2020-05-15 00:30:00   4135001  HmiyD2TTLFNqkNe            24.935753
3  2020-05-15 00:45:00   4135001  HmiyD2TTLFNqkNe            24.846130
4  2020-05-15 01:00:00   4135001  HmiyD2TTLFNqkNe            24.621525

   MODULE_TEMPERATURE  IRRADIATION
0           22.857507          0.0
1           22.761668          0.0
2           22.592306          0.0
3           22.360852          0.0
4           22.165423          0.0

In [4]:
generation_data = pd.read_csv('Combined_Generation_Data.csv')

In [5]:
weather_data= pd.read_csv('Combined_Weather_Sensor_Data.csv')

In [6]:
generation_data.groupby('PLANT_ID')['SOURCE_KEY'].nunique()

PLANT_ID
4135001    22
4136001    22
Name: SOURCE_KEY, dtype: int64

In [7]:
generation_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136476 entries, 0 to 136475
Data columns (total 7 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATE_TIME    136476 non-null  object
 1   PLANT_ID     136476 non-null  int64
 2   SOURCE_KEY   136476 non-null  object
 3   DC_POWER     136476 non-null  float64
 4   AC_POWER     136476 non-null  float64
 5   DAILY_YIELD  136476 non-null  float64
 6   TOTAL_YIELD  136476 non-null  float64
dtypes: float64(4), int64(1), object(2)
memory usage: 7.3+ MB

In [8]:
result = generation_data.groupby('PLANT_ID')['SOURCE_KEY'].nunique().reset_index()
print(result)

   PLANT_ID  SOURCE_KEY
0   4135001          22
1   4136001          22

In [9]:
# Let pandas figure out the format for each value
generation_data['DATE_TIME'] = pd.to_datetime(generation_data['DATE_TIME'], format='mixed')

In [10]:
generation_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136476 entries, 0 to 136475
Data columns (total 7 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATE_TIME    136476 non-null  datetime64[ns]
 1   PLANT_ID     136476 non-null  int64
 2   SOURCE_KEY   136476 non-null  object
 3   DC_POWER     136476 non-null  float64
 4   AC_POWER     136476 non-null  float64
 5   DAILY_YIELD  136476 non-null  float64
 6   TOTAL_YIELD  136476 non-null  float64
dtypes: datetime64[ns](1), float64(4), int64(1), object(1)
memory usage: 7.3+ MB

In [11]:
generation_data['Hour']=generation_data['DATE_TIME'].dt.hour

In [12]:
weather_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6441 entries, 0 to 6440
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   DATE_TIME            6441 non-null   object
 1   PLANT_ID             6441 non-null   int64
 2   SOURCE_KEY           6441 non-null   object
 3   AMBIENT_TEMPERATURE  6441 non-null   float64
 4   MODULE_TEMPERATURE   6441 non-null   float64
 5   IRRADIATION          6441 non-null   float64
dtypes: float64(3), int64(1), object(2)
memory usage: 302.1+ KB

In [13]:
weather_data['IsDaylight']=(weather_data['IRRADIATION']>0).astype(int)

In [14]:
weather_data['Temp_Difference'] = weather_data['MODULE_TEMPERATURE'] - weather_data['AMBIENT_TEMPERATURE']

In [15]:
generation_data.to_csv("Combined_Generation_Data_Another.csv",index=False)

In [16]:
weather_data.to_csv("Combined_Weather_Data_Another.csv",index=False)

In [17]:
result = generation_data.groupby('PLANT_ID')['DATE_TIME'].agg(lambda x: x.dt.date.nunique()).reset_index(name='nr_days')

In [18]:
result

   PLANT_ID  nr_days
0   4135001       34
1   4136001       34

In [19]:
generation_data.head()

,DATE_TIME,PLANT_ID,SOURCE_KEY,DC_POWER,AC_POWER,DAILY_YIELD,TOTAL_YIELD,Hour
0,2020-05-15,4135001,1BY6WEcLGh8j5v7,0.0,0.0,0.0,6259559.0,0
1,2020-05-15,4135001,1IF53ai7Xc0U56Y,0.0,0.0,0.0,6183645.0,0
2,2020-05-15,4135001,3PZuoBAID5Wc2HD,0.0,0.0,0.0,6987759.0,0
3,2020-05-15,4135001,7JYdWkrLSPkdwr4,0.0,0.0,0.0,7602960.0,0
4,2020-05-15,4135001,McdE0feGgRqW7Ca,0.0,0.0,0.0,7158964.0,0

In [20]:
generation_data.groupby('PLANT_ID')['DATE_TIME'].nunique()

PLANT_ID
4135001    3158
4136001    3259
Name: DATE_TIME, dtype: int64

In [21]:
generation_data['PLANT_ID'].unique()

array([4135001, 4136001])

<!DOCTYPE html>
<html>
<head>
<style>
  body {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    background: #f0f4f8;
    padding: 40px;
  }
  
  table {
    width: 100%;
    border-collapse: collapse;
  }
  
  td {
    border-radius: 20px;
  }
</style>
</head>
<body>

<!-- Option 2: Light Blue with Dark Text -->
<table style="width: 100%;">
  <tr>
    <td style="background: linear-gradient(120deg, #89f7fe 0%, #66a6ff 100%);
               padding: 50px 45px;
               border-radius: 20px;
                box-shadow: 0 10px 30px rgba(0,0,0,0.1);">
      <div style="font-size: 28px; 
                  font-weight: 800; 
                  margin-bottom: 20px;
                  color: #0c4e6e;">
        📊 Inverter Efficiency
      </div>
    </td>
  </tr>
</table>

</body>
</html>

In [22]:
result = generation_data.groupby('PLANT_ID')[['DC_POWER', 'AC_POWER']].mean().reset_index()
result.columns = ['plant_id', 'avg_dc_power', 'avg_ac_power']

print(result)

   plant_id  avg_dc_power  avg_ac_power
0   4135001   3147.426211    307.802752
1   4136001    246.701961    241.277825

In [23]:
# Calculate means first, then divide
avg_power = generation_data.groupby('PLANT_ID')[['DC_POWER', 'AC_POWER']].mean()
inv_efficiency = (avg_power['AC_POWER'] / avg_power['DC_POWER']) * 100

print(inv_efficiency)

PLANT_ID
4135001     9.779507
4136001    97.801341
dtype: float64

<!DOCTYPE html>
<html>
<head>
<style>
  body {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    background: #f0f4f8;
    padding: 40px;
  }
  
  table {
    width: 100%;
    border-collapse: collapse;
  }
  
  td {
    border-radius: 20px;
  }
</style>
</head>
<body>

<!-- Option 2: Light Blue with Dark Text -->
<table style="width: 100%;">
  <tr>
    <td style="background: linear-gradient(120deg, #89f7fe 0%, #66a6ff 100%);
               padding: 50px 45px;
               border-radius: 20px;
                box-shadow: 0 10px 30px rgba(0,0,0,0.1);">
      <div style="font-size: 28px; 
                  font-weight: 800; 
                  margin-bottom: 20px;
                  color: #0c4e6e;">
        📊 Oneof the two plants (plant_id 4135001) has a DC Power that is 10x higher
than the other. The most reasonable explanation is some kind of error in
the recording or reporting of the data.
      </div>
    </td>
  </tr>
</table>

</body>
</html>

In [24]:
generation_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136476 entries, 0 to 136475
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATE_TIME    136476 non-null  datetime64[ns]
 1   PLANT_ID     136476 non-null  int64
 2   SOURCE_KEY   136476 non-null  object
 3   DC_POWER     136476 non-null  float64
 4   AC_POWER     136476 non-null  float64
 5   DAILY_YIELD  136476 non-null  float64
 6   TOTAL_YIELD  136476 non-null  float64
 7   Hour         136476 non-null  int32
dtypes: datetime64[ns](1), float64(4), int32(1), int64(1), object(1)
memory usage: 7.8+ MB

In [25]:
import numpy as np

# Filter for specific plant
plant_data = generation_data[generation_data['PLANT_ID'] == 4136001]

# Extract hour from datetime
plant_data['hour_of_day'] = pd.to_datetime(plant_data['DATE_TIME']).dt.hour

# Create temporary columns with zeros replaced by NaN for calculations
plant_data['DC_POWER_clean'] = plant_data['DC_POWER'].replace(0, np.nan)
plant_data['AC_POWER_clean'] = plant_data['AC_POWER'].replace(0, np.nan)

# Calculate hourly aggregates
avg_dc_power_hourly=plant_data.groupby('hour_of_day')['DC_POWER'].mean()
avg_ac_power_hourly=plant_data.groupby('hour_of_day')['AC_POWER'].mean()
avg_dc_clean=plant_data.groupby('hour_of_day')['DC_POWER_clean'].mean()
avg_ac_clean=plant_data.groupby('hour_of_day')['AC_POWER_clean'].mean()

# Calculate efficiency using clean averages (excluding zeros))
inv_efficiency = round((avg_ac_clean / avg_dc_clean) * 100, 2).fillna(0)

# Display efficiency by hour
print(inv_efficiency)


hourly_effi_result = pd.DataFrame({
    'avg_dc_power': avg_dc_power_hourly.values,
    'avg_ac_power': avg_ac_power_hourly.values,
    'pct_inverter_efficiency': round((avg_ac_clean / avg_dc_clean) * 100, 2).fillna(0)
}, index=avg_dc_clean.index).reset_index()[['hour_of_day', 'avg_dc_power', 'avg_ac_power', 'pct_inverter_efficiency']]

hourly_effi_result = hourly_effi_result.sort_values('hour_of_day')

print(hourly_effi_result)

hour_of_day
0      0.00
1      0.00
2      0.00
3      0.00
4      0.00
5     96.59
6     97.14
7     98.03
8     98.03
9     97.86
10    97.73
11    97.66
12    97.64
13    97.67
14    97.78
15    97.92
16    98.04
17    97.93
18    96.94
19     0.00
20     0.00
21     0.00
22     0.00
23     0.00
dtype: float64
    hour_of_day  avg_dc_power  avg_ac_power  pct_inverter_efficiency
0             0      0.000000      0.000000                     0.00
1             1      0.000000      0.000000                     0.00
2             2      0.000000      0.000000                     0.00
3             3      0.000000      0.000000                     0.00
4             4      0.000000      0.000000                     0.00
5             5      0.003212      0.003102                    96.59
6             6     58.695532     57.017699                    97.14
7             7    244.283851    239.474513                    98.03
8             8    507.486537    497.476125                    98.03
9             9    666.983211    652.729014                    97.86
10           10    644.931525    630.284779                    97.73
11           11    645.315598    630.238819                    97.66
12           12    675.317017    659.389242                    97.64
13           13    638.724293    623.845246                    97.67
14           14    639.140549    624.959179                    97.78
15           15    595.621483    583.237962                    97.92
16           16    402.096800    394.229535                    98.04
17           17    182.920255    179.137806                    97.93
18           18     31.347465     30.389293                    96.94
19           19      0.000000      0.000000                     0.00
20           20      0.000000      0.000000                     0.00
21           21      0.000000      0.000000                     0.00
22           22      0.000000      0.000000                     0.00
23           23      0.000000      0.000000                     0.00

C:\Users\Manar\AppData\Local\Temp\ipykernel_18240\2466724395.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  plant_data['hour_of_day'] = pd.to_datetime(plant_data['DATE_TIME']).dt.hour
C:\Users\Manar\AppData\Local\Temp\ipykernel_18240\2466724395.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  plant_data['DC_POWER_clean'] = plant_data['DC_POWER'].replace(0, np.nan)
C:\Users\Manar\AppData\Local\Temp\ipykernel_18240\2466724395.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  plant_data['AC_POWER_clean'] = plant_data['AC_POWER'].replace(0, np.nan)

## ✅ *"Inverter efficiency peaks at 98.04% during medium-load conditions (244–507 kW DC), which occur in the early morning (hour 7-8) and late afternoon (hour 16)."*

✅ "At maximum power generation (hour 12, 675 kW DC), inverter efficiency is slightly lower at 97.64% due to increased thermal and switching losses."

✅ "At very low power levels (hour 5 and hour 18, <60 kW DC), efficiency drops to 96.6–97.1% due to the impact of fixed standby losses."

✅ "Nighttime hours produce zero power, and inverter efficiency is undefined/zero — not highest.

In [26]:
generation_data['SOURCE_KEY'].nunique()

44

In [27]:
weather_data['SOURCE_KEY'].nunique()

2

## There are 44 unique source keys in the first table and only 2 in the second.

In [28]:
import pandas as pd

# Load data from CSV files
Plant_1_Generation_Data = pd.read_csv('Plant_1_Generation_Data.csv')
Plant_2_Generation_Data = pd.read_csv('Plant_2_Generation_Data.csv')

# Then run your code
plant1_data = Plant_1_Generation_Data.copy()
plant1_data['PLANT_NR'] = 'plant_1'
plant1_data['DC_POWER'] = plant1_data['DC_POWER'] / 10

plant2_data = Plant_2_Generation_Data.copy()
plant2_data['PLANT_NR'] = 'plant_2'

generation_data_clean = pd.concat([plant1_data, plant2_data], ignore_index=True)

print(generation_data_clean.head())
print(f"\nTotal rows: {len(generation_data_clean)}")

          DATE_TIME  PLANT_ID       SOURCE_KEY  DC_POWER  AC_POWER  \
0  15-05-2020 00:00   4135001  1BY6WEcLGh8j5v7       0.0       0.0
1  15-05-2020 00:00   4135001  1IF53ai7Xc0U56Y       0.0       0.0
2  15-05-2020 00:00   4135001  3PZuoBAID5Wc2HD       0.0       0.0
3  15-05-2020 00:00   4135001  7JYdWkrLSPkdwr4       0.0       0.0
4  15-05-2020 00:00   4135001  McdE0feGgRqW7Ca       0.0       0.0

   DAILY_YIELD  TOTAL_YIELD PLANT_NR
0          0.0    6259559.0  plant_1
1          0.0    6183645.0  plant_1
2          0.0    6987759.0  plant_1
3          0.0    7602960.0  plant_1
4          0.0    7158964.0  plant_1

Total rows: 136476

In [29]:
import pandas as pd

# Extract hour
weather_sensor_data['hour_of_day'] = pd.to_datetime(weather_sensor_data['DATE_TIME']).dt.hour

# Group by hour and calculate means
result = weather_sensor_data.groupby('hour_of_day')[['AMBIENT_TEMPERATURE', 'MODULE_TEMPERATURE', 'IRRADIATION']].mean().reset_index()

# Add temperature difference
result['avg_temp_diff'] = result['MODULE_TEMPERATURE'] - result['AMBIENT_TEMPERATURE']

# Rename columns and round values
result.columns = ['hour_of_day', 'avg_amb_temp', 'avg_mod_temp', 'avg_irradiation', 'avg_temp_diff']
result = result.round(2)

# Sort by hour
result = result.sort_values('hour_of_day')

print(result)

    hour_of_day  avg_amb_temp  avg_mod_temp  avg_irradiation  avg_temp_diff
0             0         24.01         22.44             0.00          -1.56
1             1         23.73         22.22             0.00          -1.51
2             2         23.50         22.03             0.00          -1.47
3             3         23.32         21.85             0.00          -1.47
4             4         23.15         21.68             0.00          -1.47
5             5         23.03         21.57             0.00          -1.46
6             6         23.23         22.56             0.04          -0.67
7             7         24.42         27.76             0.19           3.33
8             8         25.98         35.35             0.38           9.36
9             9         27.55         41.81             0.55          14.26
10           10         28.91         46.37             0.67          17.46
11           11         30.12         50.08             0.75          19.96
12           12         31.10         51.76             0.76          20.66
13           13         31.56         50.14             0.69          18.58
14           14         31.75         47.46             0.59          15.71
15           15         31.42         42.95             0.45          11.53
16           16         30.92         38.08             0.29           7.16
17           17         29.95         32.51             0.13           2.56
18           18         28.34         27.59             0.02          -0.75
19           19         26.99         25.32             0.00          -1.67
20           20         26.07         24.37             0.00          -1.70
21           21         25.32         23.74             0.00          -1.58
22           22         24.65         23.08             0.00          -1.57
23           23         24.19         22.67             0.00          -1.51

In [30]:
import pandas as pd

# Extract hour
weather_sensor_data['hour_of_day'] = pd.to_datetime(weather_sensor_data['DATE_TIME']).dt.hour

# Group by hour and calculate means
result = weather_sensor_data.groupby('hour_of_day')[['AMBIENT_TEMPERATURE', 'MODULE_TEMPERATURE', 'IRRADIATION']].mean().reset_index()

# Add temperature difference
result['avg_temp_diff'] = result['MODULE_TEMPERATURE'] - result['AMBIENT_TEMPERATURE']

# Rename columns and round values
result.columns = ['hour_of_day', 'avg_amb_temp', 'avg_mod_temp', 'avg_irradiation', 'avg_temp_diff']
result = result.round(2)

# Sort by hour
result = result.sort_values('hour_of_day')

# Display the table
print(result)

# Save to Excel file (will save in the same directory as your script)
excel_filename = 'hourly_weather_data.xlsx'
result.to_excel(excel_filename, index=False, sheet_name='Hourly Weather Data')

print(f"\n✅ Data successfully saved to '{excel_filename}'")
print(f"📍 File location: {os.path.abspath(excel_filename)}")

    hour_of_day  avg_amb_temp  avg_mod_temp  avg_irradiation  avg_temp_diff
0             0         24.01         22.44             0.00          -1.56
1             1         23.73         22.22             0.00          -1.51
2             2         23.50         22.03             0.00          -1.47
3             3         23.32         21.85             0.00          -1.47
4             4         23.15         21.68             0.00          -1.47
5             5         23.03         21.57             0.00          -1.46
6             6         23.23         22.56             0.04          -0.67
7             7         24.42         27.76             0.19           3.33
8             8         25.98         35.35             0.38           9.36
9             9         27.55         41.81             0.55          14.26
10           10         28.91         46.37             0.67          17.46
11           11         30.12         50.08             0.75          19.96
12           12         31.10         51.76             0.76          20.66
13           13         31.56         50.14             0.69          18.58
14           14         31.75         47.46             0.59          15.71
15           15         31.42         42.95             0.45          11.53
16           16         30.92         38.08             0.29           7.16
17           17         29.95         32.51             0.13           2.56
18           18         28.34         27.59             0.02          -0.75
19           19         26.99         25.32             0.00          -1.67
20           20         26.07         24.37             0.00          -1.70
21           21         25.32         23.74             0.00          -1.58
22           22         24.65         23.08             0.00          -1.57
23           23         24.19         22.67             0.00          -1.51

✅ Data successfully saved to 'hourly_weather_data.xlsx'

NameError: name 'os' is not defined

## As onewould expect, irradiation is higher during the daytime and near
zero at nighttime. Also, it is interesting to note that the module
temperature is greater than the ambient at daytime and viceversa at
nighttime.

In [73]:
generation_data_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136476 entries, 0 to 136475
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   DATE_TIME    136476 non-null  object
 1   PLANT_ID     136476 non-null  int64
 2   SOURCE_KEY   136476 non-null  object
 3   DC_POWER     136476 non-null  float64
 4   AC_POWER     136476 non-null  float64
 5   DAILY_YIELD  136476 non-null  float64
 6   TOTAL_YIELD  136476 non-null  float64
 7   PLANT_NR     136476 non-null  object
dtypes: float64(4), int64(1), object(3)
memory usage: 8.3+ MB

In [74]:
generation_data_clean['DATE_TIME']=pd.to_datetime(generation_data_clean['DATE_TIME'],format='mixed')

In [75]:
# Calculate means first, then divide
avg_power = generation_data.groupby('PLANT_ID')[['DC_POWER', 'AC_POWER']].mean()
inv_efficiency = (avg_power['AC_POWER'] / avg_power['DC_POWER']) * 100

print(inv_efficiency)

PLANT_ID
4135001     9.779507
4136001    97.801341
dtype: float64

In [76]:
import pandas as pd

# Convert DATE_TIME to datetime format (add this at the beginning)
generation_data_clean['DATE_TIME'] = pd.to_datetime(generation_data_clean['DATE_TIME'])
weather_sensor_data['DATE_TIME'] = pd.to_datetime(weather_sensor_data['DATE_TIME'])

# Now your existing code will work
generation_data_clean['HOUR'] = generation_data_clean['DATE_TIME'].dt.hour
avg_power_clean = generation_data_clean.groupby('PLANT_ID')[['DC_POWER', 'AC_POWER']].mean()
gen_efficiency_clean = (avg_power_clean['AC_POWER'] / avg_power_clean['DC_POWER']) * 100

# Part 1: Generation data by PLANT_ID and hour (matching SQL subquery 'a')
gen_hourly = generation_data_clean.groupby(['PLANT_ID', 'HOUR']).agg(
    avg_dc_power=('DC_POWER', 'mean'),
    avg_ac_power=('AC_POWER', 'mean')
).reset_index()

# Calculate efficiency by hour (excluding zeros)
def calc_efficiency(group):
    dc_clean = group[group['DC_POWER'] != 0]['DC_POWER'].mean()
    ac_clean = group[group['AC_POWER'] != 0]['AC_POWER'].mean()
    if dc_clean and dc_clean != 0:
        return round((ac_clean / dc_clean) * 100, 2)
    return 0

gen_hourly['inverter_efficiency'] = generation_data_clean.groupby(['PLANT_ID', 'HOUR']).apply(calc_efficiency).values

# Part 2: Weather data by PLANT_ID and hour (matching SQL subquery 'b')
weather_sensor_data['HOUR'] = weather_sensor_data['DATE_TIME'].dt.hour

weather_hourly = weather_sensor_data.groupby(['PLANT_ID', 'HOUR']).agg(
    avg_amb_temp=('AMBIENT_TEMPERATURE', 'mean'),
    avg_mod_temp=('MODULE_TEMPERATURE', 'mean'),
    avg_irradiation=('IRRADIATION', 'mean')
).reset_index()

# Add temperature difference
weather_hourly['avg_temp_diff'] = weather_hourly['avg_mod_temp'] - weather_hourly['avg_amb_temp']

# Part 3: LEFT JOIN (same as SQL)
final_result = pd.merge(
    gen_hourly,
    weather_hourly,
    on=['PLANT_ID', 'HOUR'],
    how='left'
)

# Round numeric columns
final_result = final_result.round(2)

# Order by PLANT_ID and HOUR (same as SQL ORDER BY)
final_result = final_result.sort_values(['PLANT_ID', 'HOUR']).reset_index(drop=True)

# Rename HOUR to hour_of_day to match SQL output
final_result = final_result.rename(columns={'HOUR': 'hour_of_day'})

print(final_result)

    PLANT_ID  hour_of_day  avg_dc_power  avg_ac_power  inverter_efficiency  \
0    4135001            0          0.00          0.00                  NaN
1    4135001            1          0.00          0.00                  NaN
2    4135001            2          0.00          0.00                  NaN
3    4135001            3          0.00          0.00                  NaN
4    4135001            4          0.00          0.00                  NaN
5    4135001            5          0.00          0.00                  NaN
6    4135001            6         57.81         56.14                97.10
7    4135001            7        255.14        250.24                98.08
8    4135001            8        508.86        498.91                98.04
9    4135001            9        724.74        709.35                97.88
10   4135001           10        872.04        852.33                97.74
11   4135001           11        980.56        957.69                97.67
12   4135001           12        973.13        950.48                97.67
13   4135001           13        923.24        902.03                97.70
14   4135001           14        797.70        780.04                97.79
15   4135001           15        645.79        632.25                97.90
16   4135001           16        408.24        400.31                98.06
17   4135001           17        175.64        171.87                97.85
18   4135001           18         22.89         22.16                96.80
19   4135001           19          0.00          0.00                  NaN
20   4135001           20          0.00          0.00                  NaN
21   4135001           21          0.00          0.00                  NaN
22   4135001           22          0.00          0.00                  NaN
23   4135001           23          0.00          0.00                  NaN
24   4136001            0          0.00          0.00                  NaN
25   4136001            1          0.00          0.00                  NaN
26   4136001            2          0.00          0.00                  NaN
27   4136001            3          0.00          0.00                  NaN
28   4136001            4          0.00          0.00                  NaN
29   4136001            5          0.00          0.00                96.59
30   4136001            6         58.70         57.02                97.14
31   4136001            7        244.28        239.47                98.03
32   4136001            8        507.49        497.48                98.03
33   4136001            9        666.98        652.73                97.86
34   4136001           10        644.93        630.28                97.73
35   4136001           11        645.32        630.24                97.66
36   4136001           12        675.32        659.39                97.64
37   4136001           13        638.72        623.85                97.67
38   4136001           14        639.14        624.96                97.78
39   4136001           15        595.62        583.24                97.92
40   4136001           16        402.10        394.23                98.04
41   4136001           17        182.92        179.14                97.93
42   4136001           18         31.35         30.39                96.94
43   4136001           19          0.00          0.00                  NaN
44   4136001           20          0.00          0.00                  NaN
45   4136001           21          0.00          0.00                  NaN
46   4136001           22          0.00          0.00                  NaN
47   4136001           23          0.00          0.00                  NaN

    avg_amb_temp  avg_mod_temp  avg_irradiation  avg_temp_diff
0          22.76         20.95             0.00          -1.81
1          22.57         20.84             0.00          -1.73
2          22.46         20.77             0.00          -1.69
3          22.32         20.62             0.00          -1.69
4          22.17         20.47             0.00          -1.70
5          22.07         20.37             0.00          -1.70
6          22.21         21.29             0.04          -0.92
7          23.34         26.91             0.19           3.57
8          24.92         35.50             0.37          10.58
9          26.48         42.25             0.53          15.77
10         27.65         46.14             0.64          18.49
11         28.80         50.44             0.73          21.64
12         29.62         51.44             0.74          21.82
13         30.10         50.16             0.69          20.06
14         30.29         47.58             0.58          17.29
15         29.99         43.03             0.46          13.04
16         29.38         37.39             0.29           8.02
17         28.29         31.18             0.13           2.88
18         26.68         25.89             0.02          -0.79
19         25.36         23.44             0.00          -1.92
20         24.50         22.44             0.00          -2.06
21         23.87         21.95             0.00          -1.93
22         23.23         21.34             0.00          -1.89
23         22.89         21.09             0.00          -1.80
24         25.20         23.88             0.00          -1.32
25         24.82         23.52             0.00          -1.30
26         24.48         23.22             0.00          -1.26
27         24.27         23.01             0.00          -1.26
28         24.07         22.81             0.00          -1.26
29         23.91         22.68             0.00          -1.23
30         24.19         23.76             0.04          -0.43
31         25.48         28.58             0.19           3.10
32         27.05         35.19             0.39           8.14
33         28.61         41.37             0.57          12.76
34         30.17         46.59             0.69          16.43
35         31.43         49.72             0.76          18.29
36         32.55         52.07             0.79          19.51
37         33.01         50.12             0.69          17.11
38         33.16         47.35             0.60          14.18
39         32.81         42.87             0.44          10.06
40         32.44         38.75             0.28           6.31
41         31.59         33.83             0.12           2.25
42         30.00         29.29             0.02          -0.71
43         28.61         27.20             0.00          -1.41
44         27.63         26.29             0.00          -1.34
45         26.75         25.52             0.00          -1.23
46         26.06         24.82             0.00          -1.25
47         25.46         24.23             0.00          -1.23

C:\Users\Manar\AppData\Local\Temp\ipykernel_2164\4032249169.py:26: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  gen_hourly['inverter_efficiency'] = generation_data_clean.groupby(['PLANT_ID', 'HOUR']).apply(calc_efficiency).values

In [34]:
import pandas as pd
import os

# Convert DATE_TIME to datetime format - YOUR DATA USES DAY-MONTH-YEAR format
# Format: "15-05-2020 00:00" is day-month-year
generation_data_clean['DATE_TIME'] = pd.to_datetime(generation_data_clean['DATE_TIME'], format='%d-%m-%Y %H:%M')
weather_data['DATE_TIME'] = pd.to_datetime(weather_data['DATE_TIME'], format='%d-%m-%Y %H:%M')

# Now your existing code will work
generation_data_clean['HOUR'] = generation_data_clean['DATE_TIME'].dt.hour
avg_power_clean = generation_data_clean.groupby('PLANT_ID')[['DC_POWER', 'AC_POWER']].mean()
gen_efficiency_clean = (avg_power_clean['AC_POWER'] / avg_power_clean['DC_POWER']) * 100

# Part 1: Generation data by PLANT_ID and hour (matching SQL subquery 'a')
gen_hourly = generation_data_clean.groupby(['PLANT_ID', 'HOUR']).agg(
    avg_dc_power=('DC_POWER', 'mean'),
    avg_ac_power=('AC_POWER', 'mean')
).reset_index()

# Calculate efficiency by hour (excluding zeros)
def calc_efficiency(group):
    dc_clean = group[group['DC_POWER'] != 0]['DC_POWER'].mean()
    ac_clean = group[group['AC_POWER'] != 0]['AC_POWER'].mean()
    if dc_clean and dc_clean != 0:
        return round((ac_clean / dc_clean) * 100, 2)
    return 0

gen_hourly['inverter_efficiency'] = generation_data_clean.groupby(['PLANT_ID', 'HOUR']).apply(calc_efficiency).values

# Part 2: Weather data by PLANT_ID and hour (matching SQL subquery 'b')
weather_data['HOUR'] = weather_data['DATE_TIME'].dt.hour

weather_hourly = weather_data.groupby(['PLANT_ID', 'HOUR']).agg(
    avg_amb_temp=('AMBIENT_TEMPERATURE', 'mean'),
    avg_mod_temp=('MODULE_TEMPERATURE', 'mean'),
    avg_irradiation=('IRRADIATION', 'mean')
).reset_index()

# Add temperature difference
weather_hourly['avg_temp_diff'] = weather_hourly['avg_mod_temp'] - weather_hourly['avg_amb_temp']

# Part 3: LEFT JOIN (same as SQL)
final_result = pd.merge(
    gen_hourly,
    weather_hourly,
    on=['PLANT_ID', 'HOUR'],
    how='left'
)
# Round numeric columns
final_result = final_result.round(2)

# Order by PLANT_ID and HOUR (same as SQL ORDER BY)
final_result = final_result.sort_values(['PLANT_ID', 'HOUR']).reset_index(drop=True)

# Rename HOUR to hour_of_day to match SQL output
final_result = final_result.rename(columns={'HOUR': 'hour_of_day'})

# Display the result
print(final_result)

# Save to Excel file
excel_filename = 'plant_hourly_data.xlsx'

# Create Excel file with formatted table
with pd.ExcelWriter(excel_filename, engine='openpyxl') as writer:
    final_result.to_excel(writer, index=False, sheet_name='Plant Hourly Data')
    
    # Auto-adjust column widths
    worksheet = writer.sheets['Plant Hourly Data']
    for column in worksheet.columns:
        max_length = 0
        column_letter = column[0].column_letter
        for cell in column:
            try:
                if len(str(cell.value)) > max_length:
                    max_length = len(str(cell.value))
            except:
                pass
        adjusted_width = min(max_length + 2, 30)
        worksheet.column_dimensions[column_letter].width = adjusted_width

print(f"\n✅ Data successfully saved to '{excel_filename}'")
print(f"📊 You can now open this file in Microsoft Excel")
print(f"📍 File location: {os.path.abspath(excel_filename)}")

ValueError: time data "2020-05-15 00:00:00" doesn't match format "%d-%m-%Y %H:%M", at position 3158. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [82]:
weather_data['DATE_TIME']

0       2020-05-15 00:00:00
1       2020-05-15 00:15:00
2       2020-05-15 00:30:00
3       2020-05-15 00:45:00
4       2020-05-15 01:00:00
               ...
6436    2020-06-17 22:45:00
6437    2020-06-17 23:00:00
6438    2020-06-17 23:15:00
6439    2020-06-17 23:30:00
6440    2020-06-17 23:45:00
Name: DATE_TIME, Length: 6441, dtype: object

In [48]:
generation_data.to_csv("Combined_Generation_Data.csv",index=False)

In [49]:
weather_data.to_csv("Combines_Weather_Sensor.csv",index=False)